<div class="container p-5">
    <form action="/?pagina=clientes&acao=salvar" method="post">
        <div class="mb-3">
            <label for="nome" class="form-label">RG</label>
            <input type="nome" name="name" class="form-control" id="nome" placeholder="Nome">
        </div>
        <div class="mb-3">
            <label for="rg" class="form-labal">RG</label>
            <input type="rg" name="rg" class="form-control" id="rg" placeholder="Rg">
        </div>
        <div class="d-flex justify-content-end">
            <button class="btn btn-outline-primary">Salvar</button>
        </div>
    </form>
</div>
